### PR TITLE
device_samsung_gta4xlwifi

### PR DESCRIPTION
**Pull request by c0d3lin**
happy to contribute to the PixelExperience :)

### CODE REVIEW

**Comment by RisenID** [comment]
Why?

**Comment by c0d3lin** [comment]
i tried messaging your telegram to no avail.... am i doing this backwards here? I'm quite new to all of this

**Comment by ZIDAN44** [comment]
> i tried messaging your telegram to no avail.... am i doing this backwards here? I'm quite new to all of this

https://github.com/PixelExperience/official_devices/blob/master/README.md#1-how-to-apply

**Comment by c0d3lin** [comment]
copy that thank you!!!

**Pull request closed without merging**
