### PR TITLE
Nokia SDM660 Devices: Update the installation guide

### PR DESCRIPTION
**Pull request by userariii**

### CODE REVIEW

**Comment by RisenID** [comment]
Any reason to move almost all the install guide to a third party site instead of updating it on ours?

**Comment by userariii** [comment]
Not almost just updated the Bl unlocking method for both the devices.

It's better to refer to the unlocking tool's official website for the BL unlocking guide, as users will need to visit the site to generate the OTP for the next steps.

**Comment by RisenID** [comment]
Is this the only way to unlock the device?
Either way, why change the old guide and increase dependance on a 3rd party site that we have no control over whatsoever?

**Comment by userariii** [comment]
Yes free unlocking service is only offered by him (techmesto) & the whole Nokia community is dependent on that website for a longer time.

Previous guide is also based on that, user must visit to that website to generate the OTP

Else there's a paid method, which I can't add it here.

See Nokia don't offer the Bl unlock service officially, the only hack found by us, by using the Nokia server.

**Comment by RisenID** [comment]
I have seen the old guide and my question is why link to a site we have 0 control over for everything instead of just linking to the page where you can get the otp like earlier?

**Comment by userariii** [comment]
Ok, doing that way then.

**Pull request closed without merging**
